# data
img_size: 100
channels: 150
max_val: 6000

# model
dual_mode: false
bias_renderer: "Mean"
variance_renderer: "GaussianSkewRenderer"
mu_type: "unconstrained"
k: 5

# training
batch_size: 16
epochs: 20
lr: 0.001
device: "cuda"

# wandb
wandb: true
tags:
  - ""

# misc
save_model: false
predict_soil: true

# paths
modeller_path: ""
predictor_path: ""
submission_path: ""
