# data
img_size: 100
channels: 150
max_val: 6000

# model
dual_mode: false
bias_renderer: "Mean"
variance_renderer: "GaussianSkewRenderer" # or Autoencoder
mu_type: "unconstrained"
k: 5

# training
batch_size: 8
epochs: 20
lr: 0.001
device: "cuda"

# wandb
wandb: true
tags:
  - "hyperview"
  # - "scale_only" pass this for ablation

# misc
save_model: true
predict_soil: true

# paths
modeller_path: "output/models/hyperview.pth"
predictor_path: "output/models/hyperview.pickle"
submission_path: "output/submissions/hyperview.csv"
